from pathlib import Path
p=Path('/home/ubuntu/tech-shift/client/src/pages/Home.tsx')
s=p.read_text()
insert='''\nconst nowStack = [["AI", "Generative models, machine learning, vision, language, agents, and multimodal reasoning."], ["Cloud", "AWS, Azure, Google Cloud, serverless runtimes, and distributed systems."], ["Data", "Streaming telemetry, data lakes, warehouses, and predictive analytics."], ["Cybersecurity", "Zero-trust identity, threat detection, cloud defense, and AI-assisted response."], ["Robotics", "Industrial automation, autonomous machines, motion planning, and embodied work."], ["Quantum", "Specialized processors, superconducting qubits, and post-quantum cryptography."], ["IoT", "Smart homes, industrial sensors, connected transit, and ambient monitoring."], ["Spatial", "AR, VR, mixed reality, and 3D interfaces anchored to the physical world."]];\nconst aiActions = ["WRITE", "CODE", "ANALYZE", "SEARCH", "DESIGN", "TEST", "DEBUG", "SUMMARIZE", "PREDICT", "AUTOMATE"];\nconst futureMap = [["AUTONOMOUS AGENTS", "Core engine", "Systems that plan, use tools, execute, verify, and learn from results."], ["PHYSICAL INTELLIGENCE", "Core engine", "Vision-action models that turn perception into movement in messy spaces."], ["QUANTUM ACCELERATORS", "Core engine", "Specialized co-processors for molecular, material, and route problems."], ["SPATIAL COMPUTING", "Supporting layer", "Environment, voice, gesture, gaze, and context replace the flat screen."], ["EDGE AI", "Supporting layer", "Reasoning runs locally for speed, privacy, and offline resilience."], ["BCI + SYNTHETIC BIOLOGY", "Frontier", "Neural signals and biological code become new interfaces to compute."]];\nconst darkSectors = [["Banking + finance", "Electronic ledgers, ATMs, and cashless clearing stop. Branches cannot verify balances without centralized data."], ["Healthcare", "Networked monitors, medication controls, patient records, and automated triage become inaccessible."], ["Transportation", "Flight control, maritime routing, rail switches, ports, and fleet telemetry halt for safety."], ["Energy grids", "Real-time load balancing disappears, destabilizing generation, distribution, and cooling."], ["Manufacturing", "Robotized assembly, PLCs, and automated warehouses grind to a halt."], ["Agriculture", "Precision irrigation, sensor networks, and harvest fleets lose coordination."], ["Food distribution", "Supermarkets hold 48–72 hours of inventory; farm-to-fork routing breaks before replenishment."]];\nconst manualLadder = [["Digital payments", "Physical cash + barter"], ["GPS navigation", "Paper maps + compass"], ["Instant messaging", "Hand-delivered notes"], ["Cloud storage", "Paper ledgers"], ["Automated production", "Hand assembly"]];\nconst recoverySteps = ["Local voice comms", "Basic grid power", "Mechanical production", "Primitive compute", "Local mesh networks", "Reconnected internet", "Digital civilization"];\n'''
s=s.replace('function NowPage({ navigate }: { navigate: (view: View) => void }) {', insert+'\nfunction NowPage({ navigate }: { navigate: (view: View) => void }) {')
now_anchor='''    <section className="section container" id="pillars"><Heading'''
now_extra='''    <section className="section section-tinted" id="it-map"><div className="container"><Heading index="01B / 08" kicker="The paradigm shift" title="IT is no longer just computers." body="The old chain was computers → software → internet. The modern stack is a living infrastructure for civilization." /><div className="paradigm-compare reveal"><div><span className="mono">BEFORE</span><strong>Computers → Software → Internet</strong></div><ArrowRight size={20} /><div><span className="mono">TODAY</span><strong>AI + Cloud + Data + Robotics + Cybersecurity + Automation + IoT</strong></div></div><div className="stack-tree reveal"><div><span className="tree-label">DIGITAL</span><strong>Software · Internet · Apps</strong></div><div><span className="tree-label">INTELLIGENCE</span><strong>AI · ML · Agents</strong></div><div><span className="tree-label">INFRASTRUCTURE</span><strong>Cloud · Networks · Data centers</strong></div></div></div></section>\n    <section className="section container" id="pillars"><Heading'''
s=s.replace(now_anchor, now_extra)
now_before='''    <section className="section section-tinted" id="daily-life">'''
now_more='''    <section className="section section-tinted" id="ai-actions"><div className="container"><Heading index="03B / 08" kicker="The biggest shift" title="AI didn’t just join IT. AI is changing it." body="The action matrix is moving from passive answers toward systems that plan, use software tools, and perform work." /><div className="action-matrix reveal">{aiActions.map((action, i) => <span key={action} style={{ "--i": i } as React.CSSProperties}>{action}</span>)}</div><div className="human-ai-grid reveal"><article><Tag accent="violet">AI STRENGTHS</Tag><p>Raw speed, massive scale, tireless pattern recognition, routine automation, and 24/7 availability.</p></article><article><Tag accent="cyan">HUMAN STRENGTHS</Tag><p>Critical judgment, novel creativity, cultural context, moral ethics, leadership, empathy, and responsibility.</p></article></div><div className="plain-note"><span className="mono">CORE TAKEAWAY</span><strong>The competition is not human vs. AI.</strong><p>It is people using AI versus people who do not.</p></div></div></section>\n    <section className="section container" id="daily-life">'''
s=s.replace(now_before, now_more)
future_anchor='''    <section className="section container" id="intent-development">'''
future_extra='''    <section className="section section-tinted" id="future-map"><div className="container"><Heading index="00 / 16" kicker="Welcome to 2030" title="A trajectory, not a destination." body="Prediction is not fact. Use the confidence tags as a map of evidence, uncertainty, and frontier possibility." accent="violet" /><div className="future-map-grid">{futureMap.map(([title, type, body], i) => <article className="future-map-card reveal" key={title}><Tag accent={type === "Core engine" ? "violet" : type === "Frontier" ? "red" : "lime"}>{type}</Tag><span className="mono">0{i + 1}</span><h3>{title}</h3><p>{body}</p></article>)}</div><div className="execution-loop reveal">{["PROMPT", "REASON", "PLAN", "USE TOOLS", "EXECUTE", "VERIFY", "LEARN"].map((x, i) => <span key={x}><b>{String(i + 1).padStart(2, "0")}</b>{x}{i < 6 && <ArrowRight size={14} />}</span>)}</div></div></section>\n    <section className="section container" id="intent-development">'''
s=s.replace(future_anchor, future_extra)
future_before='''    <section className="section container" id="career-evolution">'''
future_more='''    <section className="section section-tinted" id="programming-3"><div className="container"><Heading index="05B / 16" kicker="Programming 3.0" title="The interface moves from syntax to intent." body="Python, C++, and JavaScript will not vanish overnight. But human language plus formal constraints become the primary interface for construction." accent="violet" /><div className="programming-ladder reveal">{[["Programming 1.0", "Machine-oriented", "Punch cards · Assembly · direct hardware control"], ["Programming 2.0", "Developer-oriented", "C · Java · Python · high-level abstractions"], ["Programming 3.0", "Intent + AI-oriented", "Constraints · behaviors · verification rules"]].map(([version, title, body], i) => <article key={version}><span className="mono">0{i + 1}</span><Tag accent={i === 2 ? "violet" : "cyan"}>{version}</Tag><h3>{title}</h3><p>{body}</p></article>)}</div></div></section>\n    <section className="section container" id="career-evolution">'''
s=s.replace(future_before, future_more)
dark_anchor='''    <section className="section dark-section" id="outage">'''
dark_extra='''    <section className="section dark-section" id="shutdown"><div className="container"><Heading index="00 / 14" kicker="The total shutdown" title="The world does not go dark. The world goes manual." body="Every database lock, cloud server, digital switch, and automated control loop halts simultaneously." accent="red" /><div className="shutdown-lines reveal">{["NO INTERNET.", "NO COMPUTERS.", "NO SOFTWARE.", "NO DIGITAL NETWORKS.", "NO INFORMATION TECHNOLOGY."].map((line, i) => <span key={line} style={{ "--i": i } as React.CSSProperties}>{line}</span>)}</div><div className="first-shock reveal"><span className="mono">THE FIRST SECOND → THE FIRST HOUR</span><p>Local signals vanish. Point-of-sale systems freeze. Web apps fail, GPS drops, and electronic doors default to fail-safe locks.</p></div></div></section>\n    <section className="section dark-section" id="outage">'''
s=s.replace(dark_anchor,dark_extra)
dark_before='''    <section className="section dark-section dark-section-muted" id="vulnerability">'''
dark_more='''    <section className="section dark-section dark-section-muted" id="sectors"><div className="container"><Heading index="01B / 14" kicker="Sectors that collapse" title="Nothing fails in isolation." body="The first 24 hours are not an apocalypse movie. They are a sequence of systems losing their shared coordination layer." accent="red" /><div className="sector-grid">{darkSectors.map(([title, body], i) => <article className="sector-card reveal" key={title}><span className="mono">0{i + 1} / CRITICAL</span><h3>{title}</h3><p>{body}</p></article>)}</div><div className="cascade-chain reveal">{["IT FAILURE", "COMMUNICATION", "BUSINESS", "LOGISTICS", "SUPPLY CHAIN", "SHORTAGES", "ECONOMIC CRISIS"].map((x, i) => <span key={x}>{x}{i < 6 && <ArrowRight size={14} />}</span>)}</div></div></section>\n    <section className="section dark-section dark-section-muted" id="vulnerability">'''
s=s.replace(dark_before,dark_more)
dark_res='''    <section className="section dark-section" id="resilience">'''
dark_pre_res='''    <section className="section dark-section" id="reversion"><div className="container"><Heading index="03B / 14" kicker="The great reversion" title="Digital becomes manual." body="Human knowledge, physical machinery, books, tools, and face-to-face cooperation survive. The workflow changes." accent="lime" /><div className="manual-ladder reveal">{manualLadder.map(([digital, manual], i) => <div key={digital}><strong>{digital}</strong><ArrowRight size={16} /><span>{manual}</span></div>)}</div><Heading index="03C / 14" kicker="Recovery ladder" title="Can humanity rebuild?" body="Recovery is phased: reconnect people first, then the systems that let people coordinate." accent="lime" /><div className="recovery-steps reveal">{recoverySteps.map((step, i) => <span key={step}><b>0{i + 1}</b>{step}</span>)}</div></div></section>\n    <section className="section dark-section" id="resilience">'''
s=s.replace(dark_res,dark_pre_res)
p.write_text(s)
