from pathlib import Path
p=Path('/home/ubuntu/tech-shift/client/src/pages/Home.tsx')
s=p.read_text()
marker='function DarkPage({ navigate }: { navigate: (view: View) => void }) {'
pillars='''const antifragility = [["Redundancy", "Never let one server, data center, or routing vendor hold the keys to critical life support.", "Municipal utilities, hospitals, and air transit networks need secondary and tertiary failover systems that activate instantly."], ["Offline + air-gapped backups", "Critical information must not exist solely in the cloud.", "Medical histories, land titles, legal records, and emergency manuals need immutable physical or local copies disconnected from the public internet."], ["Alternative + analog communication", "When fiber cables and cell towers fail, voice and emergency dispatch cannot go silent.", "Maintain HAM networks, high-frequency transceivers, mesh radios, and point-to-point satellite links dedicated to disaster recovery."], ["Resilient + microgrid power", "Information technology is dead silicon without electricity.", "Water plants, trauma centers, and telecom hubs need solar, geothermal, hydrogen, or other decentralized power that survives national-grid failures."], ["Human + manual skills", "Software should assist people, never replace capability entirely.", "Pilots, railway managers, grid dispatchers, and surgeons need mandatory analog drills with valves, charts, and manual switches."], ["Hardened cyber-physical security", "Treat critical civic infrastructure as sovereign defense ground.", "Disconnect grids, water plants, and nuclear systems from public access; enforce Zero Trust hardware authentication and post-quantum protocols."], ["Responsible AI + oversight", "Never surrender final life-or-death decisions to opaque automation.", "Infrastructure, medical, and emergency systems need fail-safe testing, legal accountability, and non-bypassable manual kill switches."], ["Radical decentralization", "Avoid hyper-centralized monopolistic choke points.", "Invest in open protocols, municipal software stacks, and distributed data architectures instead of a handful of hyperscalers."]];\n\n'''
s=s.replace(marker,pillars+marker)
old='''    <section className="section dark-section" id="resilience"><div className="container"><Heading index="03 / 03" kicker="The blueprint for resilience" title="Design technology that knows how to fail safely." body="This is not doom-mongering. It is an engineering wake-up call." accent="lime" /><div className="resilience-grid">{resilience.map(([title, body], i) => <article className="resilience-card reveal" key={title}><span className="resilience-number mono">0{i + 1}</span><Check size={17} /><h3>{title}</h3><p>{body}</p></article>)}</div><div className="manifest-card reveal"><Eyebrow accent="lime">True conclusion</Eyebrow><h2>THE SOLUTION IS NOT TO ABANDON TECHNOLOGY.</h2><h3>THE SOLUTION IS TO DESIGN TECHNOLOGY THAT KNOWS HOW TO FAIL SAFELY.</h3></div></div></section>'''
new='''    <section className="section dark-section" id="resilience"><div className="container"><Heading index="04 / 04" kicker="Reconstruction / architecture of survival" title="THE SOLUTION: BUILD A RESILIENT DIGITAL WORLD" body="The idea is not to remove technology or retreat into the past. Technology has elevated human health, communication, and prosperity to unprecedented heights. The objective is to make civilization less dangerously dependent on a fragile, single digital point of failure. We must build digital antifragility." accent="lime" /><div className="antifragility-grid">{antifragility.map(([title, principle, practice], i) => <article className="antifragility-card reveal" key={title}><div className="antifragility-icon" aria-hidden="true"><Check size={20} /></div><span className="mono">0{i + 1} / PILLAR</span><h3>{title}</h3><strong>{principle}</strong><p>{practice}</p></article>)}</div><div className="realization-banner reveal"><span className="mono">CORE REALIZATION</span><strong>The goal isn’t a world without technology.<br />The goal is a world that can survive when technology fails.</strong></div></div></section>'''
if old not in s: raise SystemExit('resilience block not found')
s=s.replace(old,new)
old_final='''    <section className="section final-blackout"><div className="container"><div className="final-screen reveal"><span className="mono">FINAL TRANSMISSION / 03</span><h2>WE BUILT TECHNOLOGY<br /><em>TO SERVE HUMANITY.</em></h2><h3>NOW WE MUST BUILD HUMANITY RESILIENT ENOUGH TO SURVIVE ITS TECHNOLOGY.</h3><p>The question is no longer “What can computers do?”<br />The question is “What should never be left to computers alone?”</p><div className="final-mark"><span>TECH</span><i>//</i><span>SHIFT</span></div></div></div></section>'''
new_final='''    <section className="section final-blackout"><div className="container"><div className="final-screen final-screen-manifesto reveal"><span className="mono">FINAL TRANSMISSION / 04</span><p className="manifesto-kicker">WHAT IS HAPPENING? / WHAT COULD HAPPEN NEXT? / WHAT IF IT ALL DISAPPEARED?</p><h2>THE FUTURE IS NOT SOMETHING<br /><em>WE DISCOVER.</em></h2><h3>IT IS SOMETHING WE DESIGN.</h3><p>Technology will shape the future.<br />The question is whether we shape technology first.</p><div className="final-mark"><span>TECH</span><i>//</i><span>SHIFT</span></div></div></div></section>'''
if old_final not in s: raise SystemExit('final block not found')
s=s.replace(old_final,new_final)
p.write_text(s)
