from pathlib import Path
p=Path('/home/ubuntu/tech-shift/client/src/index.css')
s=p.read_text()
s += '''

/* Light theme readability pass across NOW, 2030, and DARK SIDE */
html[data-theme="light"] body,
html[data-theme="light"] .section,
html[data-theme="light"] .hero,
html[data-theme="light"] .dark-section,
html[data-theme="light"] .final-blackout { color: #090D16; }
html[data-theme="light"] .section-heading h2,
html[data-theme="light"] .hero-title,
html[data-theme="light"] .dark-title,
html[data-theme="light"] .factor-detail h3,
html[data-theme="light"] .embodiment-copy h3,
html[data-theme="light"] .section-heading p,
html[data-theme="light"] .hero-bottom p,
html[data-theme="light"] .factor-detail p,
html[data-theme="light"] .factor-detail small,
html[data-theme="light"] .factor-list button strong,
html[data-theme="light"] .accordion-card strong,
html[data-theme="light"] .accordion-body p,
html[data-theme="light"] .plain-note p,
html[data-theme="light"] .era-card h3,
html[data-theme="light"] .era-card p,
html[data-theme="light"] .agent-compare-card h3,
html[data-theme="light"] .agent-compare-card p,
html[data-theme="light"] .hardware-grid h3,
html[data-theme="light"] .hardware-grid p,
html[data-theme="light"] .ai-field-card h3,
html[data-theme="light"] .ai-field-card p,
html[data-theme="light"] .coffee-row strong,
html[data-theme="light"] .coffee-row p,
html[data-theme="light"] .future-map-card h3,
html[data-theme="light"] .future-map-card p,
html[data-theme="light"] .programming-ladder h3,
html[data-theme="light"] .programming-ladder p,
html[data-theme="light"] .job-card h3,
html[data-theme="light"] .job-card p,
html[data-theme="light"] .cause-card strong,
html[data-theme="light"] .cause-summary,
html[data-theme="light"] .cause-expand p,
html[data-theme="light"] .manual-ladder strong,
html[data-theme="light"] .manual-ladder span,
html[data-theme="light"] .recovery-steps span,
html[data-theme="light"] .sector-card h3,
html[data-theme="light"] .sector-card p,
html[data-theme="light"] .first-shock p,
html[data-theme="light"] .outage-readout h3,
html[data-theme="light"] .outage-readout p,
html[data-theme="light"] .antifragility-card strong,
html[data-theme="light"] .antifragility-card p { color: #172033 !important; opacity: 1 !important; }
html[data-theme="light"] .factor-list button small,
html[data-theme="light"] .factor-list button > span,
html[data-theme="light"] .spatial-label,
html[data-theme="light"] .future-map-card > span:nth-child(2),
html[data-theme="light"] .programming-ladder article > span:first-child,
html[data-theme="light"] .section-number,
html[data-theme="light"] .mono { color: #475569 !important; opacity: 1 !important; }
html[data-theme="light"] .factor-list button { color: #172033; border-color: #CBD5E1; opacity: 1 !important; }
html[data-theme="light"] .factor-list button:not(.selected) strong { color: #334155 !important; }
html[data-theme="light"] .factor-list button.selected strong,
html[data-theme="light"] .factor-list button.selected > span { color: #0369A1 !important; }
html[data-theme="light"] .factor-detail { color: #172033; background: #FFFFFF; border-color: #94A3B8; }
html[data-theme="light"] .embodiment-copy p,
html[data-theme="light"] .ambient-callout,
html[data-theme="light"] .ai-field-card p { color: #334155 !important; }
html[data-theme="light"] .tag,
html[data-theme="light"] .eyebrow-mark,
html[data-theme="light"] .hero-kicker,
html[data-theme="light"] .hero-meta,
html[data-theme="light"] .nav-status { opacity: 1 !important; }
html[data-theme="light"] .site-nav .nav-link { color: #334155 !important; opacity: 1 !important; }
html[data-theme="light"] .site-nav .nav-link.active { color: #0369A1 !important; }
html[data-theme="light"] .site-nav .brand { color: #090D16 !important; }
'''
p.write_text(s)
