from pathlib import Path
p=Path('/home/ubuntu/tech-shift/client/src/pages/Home.tsx')
s=p.read_text()
old='''function Nav({ view, navigate, progress, theme, toggleTheme }: { view: View; navigate: (view: View) => void; progress: number; theme: "dark" | "light"; toggleTheme: () => void }) { return <header className="site-nav"><div className="reading-progress"><span style={{ width: `${progress}%` }} /></div><button className="brand" onClick={() => navigate("now")}><span>TECH</span><i>//</i><span>SHIFT</span></button><nav>{items.map((item) => <button key={item.id} className={`nav-link ${view === item.id ? "active" : ""}`} onClick={() => navigate(item.id)}><span className="nav-index">{item.index}</span>{item.label}</button>)}</nav><div className="nav-status"><span className="pulse-dot" /><span className="mono">4 MIN READ / {Math.round(progress)}%</span><button className="theme-toggle" onClick={toggleTheme} aria-label={`Switch to ${theme === "dark" ? "Light" : "Dark"}`} title={`Theme: ${theme === "dark" ? "Dark" : "Light"}`}><span className="theme-icon">{theme === "dark" ? <Moon size={15} /> : <Sun size={15} />}</span><span className="theme-label">THEME: {theme === "dark" ? "DARK" : "LIGHT"}</span></button></div></header>; }'''
new='''function Nav({ view, navigate, progress, theme, toggleTheme, contrast, toggleContrast, textScale, cycleTextScale }: { view: View; navigate: (view: View) => void; progress: number; theme: "dark" | "light"; toggleTheme: () => void; contrast: boolean; toggleContrast: () => void; textScale: "default" | "large" | "xlarge"; cycleTextScale: () => void }) { return <header className="site-nav"><div className="reading-progress"><span style={{ width: `${progress}%` }} /></div><button className="brand" onClick={() => navigate("now")}><span>TECH</span><i>//</i><span>SHIFT</span></button><nav>{items.map((item) => <button key={item.id} className={`nav-link ${view === item.id ? "active" : ""}`} onClick={() => navigate(item.id)}><span className="nav-index">{item.index}</span>{item.label}</button>)}</nav><div className="nav-status"><span className="pulse-dot" /><span className="mono">4 MIN READ / {Math.round(progress)}%</span><button className="accessibility-toggle" onClick={cycleTextScale} aria-label={`Text size: ${textScale}`} title={`Text size: ${textScale}. Click to enlarge.`}>A<span>{textScale === "default" ? "" : textScale === "large" ? "+" : "++"}</span></button><button className={`accessibility-toggle ${contrast ? "is-active" : ""}`} onClick={toggleContrast} aria-pressed={contrast} title="Toggle high contrast mode">HC</button><button className="theme-toggle" onClick={toggleTheme} aria-label={`Switch to ${theme === "dark" ? "Light" : "Dark"}`} title={`Theme: ${theme === "dark" ? "Dark" : "Light"}`}><span className="theme-icon">{theme === "dark" ? <Moon size={15} /> : <Sun size={15} />}</span><span className="theme-label">THEME: {theme === "dark" ? "DARK" : "LIGHT"}</span></button></div></header>; }'''
if old not in s: raise SystemExit('Nav block not found')
s=s.replace(old,new)
old_acc='''function Accordion({ title, plain, body, icon: Icon, accent, open, onClick }: { title: string; plain: string; body: string; icon: React.ElementType; accent: string; open: boolean; onClick: () => void }) { return <article className={`accordion-card accent-${accent} ${open ? "open" : ""}`}><button onClick={onClick}><span className="accordion-icon"><Icon size={18} /></span><span><strong>{title}</strong><small>PLAIN ENGLISH / {plain}</small></span><ChevronDown size={16} /></button>{open && <div className="accordion-body"><p>{body}</p><span className="mono">WHY IT MATTERS</span></div>}</article>; }'''
new_acc='''function Accordion({ title, plain, body, icon: Icon, accent, open, onClick }: { title: string; plain: string; body: string; icon: React.ElementType; accent: string; open: boolean; onClick: () => void }) { return <article className={`accordion-card accent-${accent} technology-card ${open ? "open" : ""}`} data-tooltip={`${title}: ${plain}`}><button onClick={onClick} aria-expanded={open}><span className="accordion-icon"><Icon size={18} /></span><span><strong>{title}</strong><small>PLAIN ENGLISH / {plain}</small></span><ChevronDown size={16} /></button>{open && <div className="accordion-body"><p>{body}</p><span className="mono">WHY IT MATTERS</span></div>}</article>; }'''
if old_acc not in s: raise SystemExit('Accordion block not found')
s=s.replace(old_acc,new_acc)
old_map='''<article className="future-map-card reveal" key={title}><span className="mono">{label}</span><span className="mono">0{i + 1}</span><h3>{title}</h3><p>{body}</p></article>'''
new_map='''<article className="future-map-card technology-card reveal" key={title} data-tooltip={`${label}: ${body}`}><span className="mono">{label}</span><span className="mono">0{i + 1}</span><h3>{title}</h3><p>{body}</p></article>'''
s=s.replace(old_map,new_map)
old_state='''  const [theme, setTheme] = useState<"dark" | "light">(() => { const saved = localStorage.getItem("tech-shift-theme"); return saved === "light" || saved === "pitch" ? "light" : "dark"; });'''
new_state='''  const [theme, setTheme] = useState<"dark" | "light">(() => { const saved = localStorage.getItem("tech-shift-theme"); return saved === "light" || saved === "pitch" ? "light" : "dark"; });
  const [contrast, setContrast] = useState(() => localStorage.getItem("tech-shift-contrast") === "high");
  const [textScale, setTextScale] = useState<"default" | "large" | "xlarge">(() => { const saved = localStorage.getItem("tech-shift-text-scale"); return saved === "large" || saved === "xlarge" ? saved : "default"; });'''
if old_state not in s: raise SystemExit('state block not found')
s=s.replace(old_state,new_state)
old_effect='''  useEffect(() => { document.documentElement.dataset.theme = theme; localStorage.setItem("tech-shift-theme", theme); }, [theme]);'''
new_effect='''  useEffect(() => { document.documentElement.dataset.theme = theme; localStorage.setItem("tech-shift-theme", theme); }, [theme]);
  useEffect(() => { document.documentElement.dataset.contrast = contrast ? "high" : "standard"; localStorage.setItem("tech-shift-contrast", contrast ? "high" : "standard"); }, [contrast]);
  useEffect(() => { document.documentElement.dataset.textScale = textScale; localStorage.setItem("tech-shift-text-scale", textScale); }, [textScale]);'''
if old_effect not in s: raise SystemExit('theme effect not found')
s=s.replace(old_effect,new_effect)
old_return='''<Nav view={view} navigate={navigate} progress={progress} theme={theme} toggleTheme={() => setTheme((current) => current === "dark" ? "light" : "dark")} />'''
new_return='''<Nav view={view} navigate={navigate} progress={progress} theme={theme} toggleTheme={() => setTheme((current) => current === "dark" ? "light" : "dark")} contrast={contrast} toggleContrast={() => setContrast((current) => !current)} textScale={textScale} cycleTextScale={() => setTextScale((current) => current === "default" ? "large" : current === "large" ? "xlarge" : "default")} />'''
if old_return not in s: raise SystemExit('Nav usage not found')
s=s.replace(old_return,new_return)
p.write_text(s)
