from pathlib import Path

p = Path('/home/ubuntu/tech-shift/client/src/pages/Home.tsx')
s = p.read_text()

start = s.index('function FuturePage(')
end = s.index('function DarkPage()', start)
future = r'''function FuturePage({ navigate }: { navigate: (view: View) => void }) {
  const [openShift, setOpenShift] = useState(() => Number(q("shift", "0")));
  const [filter, setFilter] = useState(() => q("filter", "ALL"));
  const visible = filter === "ALL" ? frontiers : frontiers.filter((x) => x[1] === filter);
  const softwareEras = [["1980s–2010s", "SYNTAX ERA", "Developers memorize C, Java, and Python. A missing bracket can break the whole program."], ["2020–2025", "ASSISTED ERA", "Programmers write prompts and snippets while AI autocompletes lines and generates functions."], ["2030", "INTENT ERA", "Engineers declare business logic, security policies, and performance budgets. Agent swarms draft, test, and deploy the system."]];
  const agentRows = [["Current conversational AI", "PASSIVE", ["Needs constant human prompts", "Generates text answers", "Little cross-session state"]], ["2030 agent swarms", "ACTIVE + PROACTIVE", ["Self-plans and uses tools", "Agents cross-verify each other", "Humans approve high-impact edge cases"]]];
  return <Page view="future">
    <section className="hero educational-hero hero-future"><div className="future-scanlines" /><div className="hero-content container"><div className="hero-meta reveal"><span>FIELD NOTE 002 / PROJECTION</span><span>APPROX. 04 MIN</span></div><div className="hero-kicker reveal"><span className="pulse-dot" /> FOLLOW THE FOOTPRINTS / CALIBRATE YOUR CERTAINTY</div><h1 className="hero-title reveal">THE DISSOLUTION<br /><em>OF THE</em><br /><span>COMPUTER.</span></h1><div className="hero-bottom reveal"><p>Computing in 2030 will not be confined to glass slabs in our pockets. It becomes ambient, intent-driven, and physically embodied in our living environment.</p><div className="certainty-legend"><Tag accent="lime">HIGH CONFIDENCE / LIKELY</Tag><Tag accent="amber">MEDIUM CONFIDENCE / PLAUSIBLE</Tag><Tag accent="red">FRONTIER / SPECULATIVE</Tag></div></div></div></section>
    <section className="section container" id="intent-development"><Heading index="01 / 05" kicker="Evolution of software engineering" title="Intent becomes the new syntax." body="The language changes. The responsibility does not: someone still has to define what good means." accent="violet" /><div className="era-grid reveal">{softwareEras.map(([period, title, body], i) => <article className={`era-card era-${i}`} key={period}><span className="mono">{period}</span><Tag accent={i === 2 ? "violet" : i === 1 ? "amber" : "cyan"}>{title}</Tag><h3>{i === 0 ? "Syntax" : i === 1 ? "Assistance" : "Architecture"}</h3><p>{body}</p>{i === 2 && <div className="era-callout"><Check size={15} /> 80% of the work shifts toward design, verification, security, and business logic.</div>}</article>)}</div><div className="plain-note reveal"><span className="mono">THE BIG SHIFT</span><strong>From writing functions to designing systems.</strong><p>Boilerplate becomes cheap. Judgment, constraints, threat modeling, and verification become the scarce skills.</p></div></section>
    <section className="section section-tinted" id="agent-swarms"><div className="container"><Heading index="02 / 05" kicker="Autonomous agent swarms" title="A chatbot answers. A swarm operates." body="The difference is not personality. It is state, tool use, delegation, and accountability." accent="violet" /><div className="agent-compare reveal">{agentRows.map(([title, state, bullets], i) => <article className={`agent-compare-card agent-${i}`} key={title}><div className="agent-card-top"><Tag accent={i === 0 ? "amber" : "violet"}>{state}</Tag><span className="mono">0{i + 1}</span></div><h3>{title}</h3><ul>{bullets.map((bullet) => <li key={bullet}><Check size={14} />{bullet}</li>)}</ul><p>{i === 0 ? "You ask, it responds, you execute." : "You define the objective; specialized agents plan, negotiate, verify, and surface only the decisions that need human approval."}</p></article>)}</div><div className="agent-scenario reveal"><span className="mono">SCENARIO / CLOUD COST AUDIT</span><strong>“Audit cloud spending, find idle clusters, test downtime risk, and spin them down during non-peak hours.”</strong><div><span>Security Agent audits</span><ArrowRight size={15} /><span>Feature Agent drafts</span><ArrowRight size={15} /><span>DevOps Agent deploys</span></div></div></div></section>
    <section className="section container" id="embodiment"><Heading index="03 / 05" kicker="Physical intelligence" title="Software gets a body." body="Foundation vision-action models let AI navigate three-dimensional spaces, not only digital text." accent="violet" /><div className="embodiment-grid reveal"><div className="embodiment-visual"><div className="spatial-orbit" /><div className="spatial-core"><Cpu size={28} /><span>VISION<br />→ ACTION</span></div><div className="spatial-label spatial-a">WAREHOUSE / LOGISTICS</div><div className="spatial-label spatial-b">CARE / ASSISTANCE</div><div className="spatial-label spatial-c">AGRICULTURE / PICKING</div></div><div className="embodiment-copy"><h3>Adaptive, not pre-programmed.</h3><p>Warehouse robots, construction machines, delivery drones, and care assistants learn from physical demonstrations. The environment is no longer a fixed set of rules — it is a changing context to interpret.</p><div className="ambient-callout"><Globe2 size={17} /><span>A technician looking at an aircraft engine sees live thermal diagnostics anchored directly to the machinery.</span></div></div></div></section>
    <section className="section section-tinted" id="hardware-frontier"><div className="container"><Heading index="04 / 05" kicker="The next hardware frontier" title="Beyond traditional silicon." body="The useful question is not “Is it faster?” It is “What new constraints does it remove?”" accent="violet" /><div className="hardware-grid reveal"><article><BrainCircuit size={21} /><Tag accent="violet">NEUROMORPHIC</Tag><h3>Brains, not clocks.</h3><p>Event-based chips draw power only when incoming signals change, making local reasoning practical for wearables, implants, and drones.</p><strong>DAYS OR WEEKS OF BATTERY LIFE</strong></article><article><Binary size={21} /><Tag accent="amber">QUANTUM</Tag><h3>A specialist, not a replacement.</h3><p>Quantum systems act as cloud co-processors for molecular simulation, battery chemistry, and global route optimization.</p><strong>NEW PROBLEM CLASSES</strong></article><article><Wifi size={21} /><Tag accent="lime">EDGE AI</Tag><h3>Compute comes home.</h3><p>Reasoning runs locally on rings, traffic sensors, and medical devices — reducing latency and keeping sensitive data closer to its source.</p><strong>DATA SOVEREIGNTY</strong></article></div></div></section>
    <section className="section container" id="career-evolution"><Heading index="05 / 05" kicker="Job market + career evolution" title="The work moves up the stack." body="Some repetitive tasks decline. The work of designing, auditing, securing, and humanizing systems multiplies." accent="violet" /><div className="jobs-grid expanded-jobs">{[["Roles declining", "Rote syntax coding, manual test scripts, basic formatting, repetitive scraping", "red"], ["AI Agent Architect", "Designs workflows, permissions, and tool ecosystems for multi-agent systems.", "violet"], ["AI Safety + Algorithmic Auditor", "Evaluates bias, hallucination rates, and regulatory compliance.", "lime"], ["Cyber-Physical Systems Engineer", "Secures municipal grids, robotic fleets, and medical hardware.", "cyan"], ["Human-AI Interaction Designer", "Creates intuitive feedback loops for non-technical users.", "amber"]].map(([title, body, accent], i) => <article className={`job-card accent-${accent} reveal`} key={title}><span className="mono">0{i + 1}</span><h3>{title}</h3><p>{body}</p></article>)}</div><div className="transition-cta dark-cta reveal"><div><Eyebrow accent="red">Final question</Eyebrow><h3>WHAT HAPPENS IF THE PLUG IS PULLED?</h3><p>We are building the most powerful technological web in human history. That makes resilience part of the design brief.</p></div><button className="primary-button button-red" onClick={() => navigate("dark")}>ENTER THE DARK SIDE <ArrowRight size={17} /></button></div></section>
  </Page>;
}

'''
s = s[:start] + future + s[end:]

old = '''{openCause === i && <p>{body}</p>}'''
new = '''<div className="cause-expand"><p>{body}</p><span className="mono">DEPENDENCY BREAKDOWN / {openCause === i ? "VISIBLE" : "READY"}</span></div>'''
s = s.replace(old, new)
s = s.replace('const vulnerabilities = [["The just-in-time trap", "Algorithms order supplies hours before they are needed. Remove IT and the pipeline empties immediately."], ["Loss of manual redundancy", "Two generations have never operated a railway switch, calculated navigation charts, or kept paper ledgers."], ["Hyper-interconnectedness", "Banking depends on telecom; telecom on power; power on cooling; cooling on water logistics."], ["Invisible dependency", "The most important infrastructure is the infrastructure people stop noticing."]];', '''const vulnerabilities = [["The Just-In-Time (JIT) supply trap", "Supermarkets and pharmacies hold only 48–72 hours of inventory. Digital inventory algorithms trigger replenishment hours before shelves empty. If routing, payment processing, or fuel software fails, the delivery pipeline freezes instantly."], ["Loss of analog + manual competence", "Modern workers lack practice with non-digital workflows. Two generations have relied on GPS, computerized dispatching, automated valves, and digital medical charts. Paper ledgers and manual gauges cause severe slowdowns when tools go offline."], ["Hyper-interconnected systemic cascades", "Water treatment depends on power; power plants depend on cooling water and computerized valves; telecom switches require steady grid power; technicians repairing grids need telecom and digital banking for fuel."], ["Concentration of digital infrastructure", "The modern internet relies on a handful of cloud providers, fiber-optic choke points, and centralized DNS registries. A single bug or concentrated disruption can knock out thousands of public services."]];''')
p.write_text(s)

css = Path('/home/ubuntu/tech-shift/client/src/index.css')
styles = css.read_text()
styles += '''

/* Readability and Page 02 expansion */
body { color: #e2e8f0; font-size: 18px; line-height: 1.75; }
.section-heading h2 { font-size: clamp(36px, 4vw, 58px); }
.section-heading p, .hero-bottom p, .accordion-body p, .plain-note p, .factor-detail p, .ai-field-card p, .coffee-row p, .shift-body > p, .frontier-card p, .job-card p, .cause-expand p, .resilience-card p { font-size: 18px; line-height: 1.75; }
.accordion-card, .factor-detail, .ai-field-card, .coffee-table, .shift-card, .frontier-card, .job-card, .cause-card, .resilience-card, .manifest-card { background: #14171f; }
.era-grid, .agent-compare, .hardware-grid { display: grid; grid-template-columns: repeat(3, 1fr); gap: 12px; }
.era-card, .agent-compare-card, .hardware-grid article { min-height: 300px; padding: 28px; border: 1px solid var(--line); background: #14171f; }
.era-card > span:first-child, .agent-card-top > span:last-child { display: block; color: #7d8b89; font-size: 11px; }
.era-card > .tag { display: inline-block; margin-top: 26px; }
.era-card h3, .agent-compare-card h3, .hardware-grid h3 { margin: 22px 0 10px; color: #e2e8f0; font: 500 28px/1 var(--display); letter-spacing: -.06em; }
.era-card p, .agent-compare-card p, .hardware-grid p { margin: 0; color: #aeb9b7; font-size: 17px; line-height: 1.7; }
.era-callout { display: flex; gap: 8px; align-items: flex-start; margin-top: 24px; padding-top: 16px; border-top: 1px solid var(--line); color: var(--violet); font-size: 14px; line-height: 1.5; }
.agent-compare { grid-template-columns: 1fr 1fr; }
.agent-card-top { display: flex; justify-content: space-between; }
.agent-compare-card ul { display: flex; flex-direction: column; gap: 10px; margin: 26px 0; padding: 0; list-style: none; color: #b4c0bd; font-size: 16px; }
.agent-compare-card li { display: flex; gap: 9px; align-items: flex-start; }.agent-compare-card li svg { flex: 0 0 auto; margin-top: 5px; color: var(--violet); }.agent-compare-card p { color: #7f8c89; font-size: 15px; }.agent-1 { border-color: rgba(168,85,247,.45); }
.agent-scenario { margin-top: 15px; padding: 22px 28px; border: 1px solid rgba(168,85,247,.35); background: rgba(168,85,247,.06); }.agent-scenario > span { color: var(--violet); font-size: 10px; }.agent-scenario strong { display: block; max-width: 780px; margin: 12px 0 19px; color: #d8c8e8; font: 500 22px/1.25 var(--display); }.agent-scenario > div { display: flex; flex-wrap: wrap; align-items: center; gap: 10px; color: #a58cb9; font: 12px var(--mono); }.agent-scenario svg { color: var(--violet); }
.embodiment-grid { display: grid; grid-template-columns: 1.1fr 1fr; gap: 50px; align-items: center; }.embodiment-visual { position: relative; min-height: 410px; overflow: hidden; border: 1px solid rgba(168,85,247,.32); background: radial-gradient(circle, rgba(168,85,247,.14), transparent 35%), #0b0910; }.spatial-orbit { position: absolute; inset: 18%; border: 1px solid rgba(168,85,247,.35); border-radius: 50%; transform: rotate(26deg) scaleX(1.7); animation: orbit-drift 16s ease-in-out infinite alternate; }.spatial-core { position: absolute; left: 50%; top: 50%; display: grid; place-items: center; width: 150px; height: 150px; gap: 8px; border: 1px solid var(--violet); border-radius: 50%; color: var(--violet); transform: translate(-50%,-50%); box-shadow: 0 0 50px rgba(168,85,247,.23); }.spatial-core span { font: 10px/1.25 var(--mono); text-align: center; }.spatial-label { position: absolute; color: #a68eb8; font: 9px var(--mono); }.spatial-a { top: 20%; left: 8%; }.spatial-b { right: 5%; top: 68%; }.spatial-c { left: 14%; bottom: 15%; }.embodiment-copy h3 { margin: 0 0 15px; color: #e2e8f0; font: 500 34px/1 var(--display); letter-spacing: -.07em; }.embodiment-copy p { margin: 0; color: #aeb9b7; font-size: 18px; line-height: 1.75; }.ambient-callout { display: flex; gap: 12px; margin-top: 30px; padding: 18px; border-left: 2px solid var(--violet); background: rgba(168,85,247,.07); color: #c9b8d7; font-size: 16px; line-height: 1.55; }.ambient-callout svg { flex: 0 0 auto; color: var(--violet); }
.hardware-grid { grid-template-columns: repeat(3, 1fr); }.hardware-grid article > svg { color: var(--violet); }.hardware-grid article > .tag { display: block; width: fit-content; margin-top: 23px; }.hardware-grid article strong { display: block; margin-top: 24px; padding-top: 13px; border-top: 1px solid var(--line); color: var(--violet); font: 11px var(--mono); }.expanded-jobs { grid-template-columns: repeat(5, 1fr); }
.cause-card { overflow: visible; }.cause-card button { padding: 24px 28px; }.cause-expand { display: grid; grid-template-rows: 1fr; padding: 0 28px 24px 80px; border-top: 1px solid rgba(255,255,255,.12); }.cause-expand p { margin: 18px 0 12px; color: #b4c0bd; }.cause-expand .mono { color: var(--red); font-size: 10px; }
@media (max-width: 900px) { .era-grid, .hardware-grid { grid-template-columns: 1fr; }.embodiment-grid { grid-template-columns: 1fr; }.expanded-jobs { grid-template-columns: repeat(2, 1fr); } }
@media (max-width: 620px) { body { font-size: 17px; }.section-heading p, .hero-bottom p, .accordion-body p, .plain-note p, .factor-detail p, .ai-field-card p, .coffee-row p, .shift-body > p, .frontier-card p, .job-card p, .cause-expand p, .resilience-card p { font-size: 17px; }.era-card, .agent-compare-card, .hardware-grid article { padding: 22px; }.agent-compare { grid-template-columns: 1fr; }.expanded-jobs { grid-template-columns: 1fr; }.embodiment-visual { min-height: 330px; }.cause-card button { padding: 19px; }.cause-expand { padding-left: 19px; padding-right: 19px; } }
'''
css.write_text(styles)
