from pathlib import Path
p=Path('/home/ubuntu/tech-shift/client/src/index.css')
s=p.read_text()
s += '''

/* DARK SIDE reconstruction ending */
.antifragility-grid { display: grid; grid-template-columns: repeat(4,1fr); gap: 12px; }.antifragility-card { min-height: 330px; padding: 22px; border: 1px solid var(--border-color); background: var(--bg-surface); box-shadow: 0 4px 14px rgba(0,0,0,.06); transition: transform .2s var(--ease-out), border-color .2s, box-shadow .2s; }.antifragility-card:hover { transform: translateY(-4px); border-color: var(--accent-cyan); box-shadow: 0 12px 26px rgba(0,0,0,.14); }.antifragility-icon { display: grid; place-items: center; width: 42px; height: 42px; margin-bottom: 22px; border: 1px solid var(--accent-cyan); border-radius: 50%; color: var(--accent-cyan); background: var(--accent-cyan-bg, rgba(2,132,199,.08)); }.antifragility-card > span { color: var(--text-muted); font-size: 10px; }.antifragility-card h3 { margin: 24px 0 12px; color: var(--text-primary); font: 500 22px/1.1 var(--display); }.antifragility-card strong { display: block; color: var(--text-primary); font-size: 18px; line-height: 1.55; }.antifragility-card p { margin: 13px 0 0; color: var(--text-secondary); font-size: 18px; line-height: 1.75; }.realization-banner { margin-top: 24px; padding: 32px; border: 1px solid var(--accent-lime, var(--lime)); background: color-mix(in srgb, var(--bg-surface) 82%, var(--accent-cyan)); }.realization-banner .mono { display: block; margin-bottom: 14px; color: var(--accent-cyan); font-size: 11px; }.realization-banner strong { color: var(--text-primary); font: 500 clamp(24px,3.2vw,42px)/1.12 var(--display); }.final-screen-manifesto { min-height: 100vh; display: flex; flex-direction: column; justify-content: center; align-items: center; text-align: center; }.manifesto-kicker { max-width: 800px; margin: 32px auto; color: var(--text-muted); font: 11px var(--mono); letter-spacing: .09em; }.final-screen-manifesto h2 { margin: 0; color: var(--text-primary); font-size: clamp(42px,6vw,78px); line-height: .98; }.final-screen-manifesto h2 em { color: var(--accent-cyan); }.final-screen-manifesto h3 { max-width: 720px; margin: 18px 0 0; color: var(--text-primary); font: 500 clamp(28px,4vw,54px)/1.03 var(--display); }.final-screen-manifesto > p:not(.manifesto-kicker) { margin: 32px 0 44px; color: var(--text-secondary); font-size: 20px; line-height: 1.75; }.final-screen-manifesto .final-mark { margin-top: 0; }
html[data-theme="light"] .antifragility-card { box-shadow: 0 4px 14px rgba(0,0,0,.06); } html[data-theme="light"] .realization-banner { border-color: #0284C7; background: #E0F2FE; } html[data-theme="light"] .realization-banner strong, html[data-theme="light"] .final-screen-manifesto h2, html[data-theme="light"] .final-screen-manifesto h3 { color: #090D16; } html[data-theme="light"] .final-screen-manifesto h2 em { color: #0284C7; }
@media (max-width: 1000px) { .antifragility-grid { grid-template-columns: repeat(2,1fr); } }
@media (max-width: 620px) { .antifragility-grid { grid-template-columns: 1fr; }.antifragility-card { min-height: 0; }.realization-banner { padding: 23px; }.final-screen-manifesto h2 { font-size: 44px; }.final-screen-manifesto h3 { font-size: 31px; }.manifesto-kicker { line-height: 1.7; } }
'''
p.write_text(s)
