import { useEffect, useMemo, useState } from "react";
import {
  ArrowDown, ArrowDownRight, ArrowRight, ArrowUpRight, Binary, BrainCircuit, Check, ChevronDown,
  ChevronRight, CircleAlert, Cloud, Code2, Cpu, Database, GitBranch, Globe2, HardDrive,
  Layers3, LockKeyhole, Network, Radio, Server, ShieldCheck, Sparkles, Terminal, Wifi, Workflow, Moon, Sun,
} from "lucide-react";

type View = "now" | "future" | "dark";
type Item = { id: View; index: string; label: string };
const items: Item[] = [{ id: "now", index: "01", label: "NOW" }, { id: "future", index: "02", label: "2030" }, { id: "dark", index: "03", label: "DARK SIDE" }];

function q(key: string, fallback: string) { return new URLSearchParams(window.location.search).get(key) || fallback; }
function linkState(view: View, values: Record<string, string | number> = {}) { const url = new URL(window.location.href); url.hash = view; Object.entries(values).forEach(([k, v]) => url.searchParams.set(k, String(v))); window.history.replaceState(null, "", `${url.pathname}${url.search}${url.hash}`); }
function jump(view: View, section: string, values: Record<string, string | number> = {}) { linkState(view, { section, ...values }); }

const pillars = [
  ["Hardware", "The concrete & steel", "The physical machines you can touch: servers, microchips, undersea cables, and mobile processors.", "Without silicon chips smaller than a grain of rice, no software can run.", "cyan", Cpu],
  ["Software", "The rooms & appliances", "Step-by-step instructions written in programming languages that tell hardware what to do.", "Software turns raw electricity into video calls, medical imaging, and spreadsheets.", "violet", Code2],
  ["Networks + Cloud", "The plumbing & roads", "Satellites, towers, fiber, and data centers moving data worldwide in milliseconds.", "The Cloud is simply someone else’s computer — usually thousands of warehouse servers.", "lime", Cloud],
  ["Data + AI", "The brain & memory", "Every click, payment, heartbeat, and the algorithms that find patterns in that noise.", "Software used to follow rules. Today’s AI learns patterns from data.", "amber", BrainCircuit],
] as const;
const acceleration = [
  ["01", "Exponential compute", "MOORE’S LEGACY", "Billions of microscopic transistors now fit on postage-stamp-sized chips.", "More compute makes more ambitious software economically possible."],
  ["02", "The data avalanche", "RAW MATERIAL", "Billions of connected devices generate new examples every second.", "Patterns hide inside the noise — if you have enough of it."],
  ["03", "Open-source collaboration", "SHARED LEVERAGE", "Developers share code globally instead of rebuilding the same wheel.", "Every release becomes a launchpad for the next one."],
  ["04", "The recursive AI loop", "SPEED MULTIPLIER", "AI writes tools that design chips that train more capable AI.", "The system is now helping improve the system."],
];
const aiFields = [
  ["Software engineering", "AI writes boilerplate and flags security bugs — shifting the programmer from typist to architect and reviewer.", Code2, "cyan"],
  ["Healthcare", "AI screens chest X-rays in seconds, flagging anomalies human eyes might miss during a 12-hour shift.", ShieldCheck, "red"],
  ["Logistics", "Predictive algorithms route ships around storms and balance warehouse inventory before items sell out.", Network, "lime"],
  ["Cybersecurity", "Algorithms fight machine-speed attacks where human reflexes are simply too slow to intervene.", LockKeyhole, "violet"],
] as const;
const coffee = [["06:30 / Alarm", "RTC chip + GPS sync", "An embedded clock syncs through cellular networks to atomic clocks carried by GPS satellite constellations."], ["06:45 / Water + kettle", "Microcontrollers + utility telemetry", "Sensors watch flow and pressure while municipal dashboards monitor the network behind an ordinary cup of water."], ["07:15 / Grocery payment", "NFC + encrypted token + distributed databases", "A tap routes a token through a payment gateway, verifies funds, and returns approval in roughly 400 milliseconds."], ["07:30 / Bus ride", "GPS + 5G telematics + route optimization", "A moving vehicle transmits coordinates to engines that update arrival times on thousands of phones at once."]];
const shifts = [
  ["From syntax to intent", "LIKELY", "Today you speak Python, C++, or Java. By 2030, you describe goals, constraints, and architecture; agent swarms assemble and maintain the software.", "Like moving from typing GPS coordinates to saying: take me there, avoid tolls, and arrive before 8."],
  ["From tools to autonomous agents", "PLAUSIBLE", "Instead of opening apps to book a trip, you give an objective. An agent negotiates APIs, resolves conflicts, and delivers the boarding pass.", "Like hiring a tireless executive assistant who can actually push the buttons."],
  ["Physical intelligence", "LIKELY", "Vision models and reinforcement learning move out of data centers and into robots, drones, and assistive care machines.", "Like giving software a body — and then teaching it to navigate the messy real world."],
];
const frontiers = [["Neuromorphic computing", "PLAUSIBLE", "Chips that mimic biological neurons, firing only when information changes.", "Battery life could shift from hours to weeks."], ["Quantum computing", "FRONTIER / SPECULATIVE", "Systems that calculate across multi-dimensional states.", "Molecular modeling, batteries, and cryptography are the target problems."], ["Spatial + ambient computing", "LIKELY", "Lightweight eyewear and audio wearables project context onto reality.", "The monitor dissolves into the room around you."], ["Edge AI", "LIKELY", "Powerful reasoning models run directly on local devices.", "Smart rings and traffic sensors can act without an active internet connection."]];
const jobs = [["What fades away", "Pure rote coding, manual testing, data entry, basic script writing.", "red"], ["AI Systems Architects", "Design and orchestrate interacting swarms of AI agents.", "violet"], ["Safety + Alignment Auditors", "Verify automated systems make ethical, unbiased, safe decisions.", "lime"], ["Cyber-Physical Security Engineers", "Protect water plants and autonomous grids from digital tampering.", "cyan"], ["Human-Machine Experience Designers", "Keep autonomous tools intuitive, empathetic, and controllable.", "amber"]];
const outage = [["00:00", "Core backbone loss", "Fiber routing and cellular handshake protocols fail. Landlines overload within minutes."], ["03:00", "Financial + commerce gridlock", "Payment networks and ATMs lock up. Registers cannot scan barcodes or calculate taxes."], ["12:00", "Logistics + transport freeze", "Air traffic reverts to manual separation. GPS, fuel dispatch, and warehouse systems go dark."], ["24:00", "Utilities + healthcare strain", "Water loses automated valves and dosage sensors. Hospitals rely on generators, memory, and paper charts."], ["72:00", "The systemic food cliff", "Supermarkets hold only two to three days of food. Without coordinated deliveries, shelves run empty."]];
const vulnerabilities = [["The Just-In-Time supply trap", "Modern logistics avoids warehouse storage to cut costs, relying on algorithms to deliver goods hours before they are needed. With no municipal food caches, a glitch in tracking, fuel dispatch, or payment software can empty shelves within 48 hours."], ["Loss of manual redundancy", "Multiple generations have worked with zero analog tools. Train signals, grid switches, flight paths, and medical triage are digital; few operators can calculate paper charts or manage mechanical systems under pressure."], ["The web of interconnected dependencies", "Water pumps require electricity; power plants require cooling and automated valves; technicians require telecommunications; repair teams require digital payment cards to buy fuel. When one pillar cracks, the rest stumble."], ["Concentration of digital infrastructure", "A small number of cloud, DNS, and undersea-cable chokepoints carry enormous public-service load. Concentration turns a local defect into a systemic event."]];

const vulnerabilitySummaries = ["Algorithms trade warehouse stock for delivery speed.", "Critical workers have lost practice with analog fallbacks.", "Every critical service depends on several others.", "A few infrastructure chokepoints carry enormous public load."];
const resilience = [["Graceful degradation", "Fail step-by-step into manual modes — never crash all at once."], ["Air-gapped redundancy", "Keep critical water, power, and emergency systems able to operate offline."], ["Decentralized architectures", "Mesh networks and local microgrids should function when the backbone is severed."], ["Analog competence", "Train human operators to manage flights, grids, and triage without digital assistance."]];

function Eyebrow({ children, accent = "cyan" }: { children: React.ReactNode; accent?: string }) { return <div className={`eyebrow eyebrow-${accent}`}><span className="eyebrow-mark" />{children}</div>; }
function Tag({ children, accent = "cyan" }: { children: React.ReactNode; accent?: string }) { return <span className={`tag tag-${accent}`}>{children}</span>; }
function Heading({ index, kicker, title, body, accent = "cyan" }: { index: string; kicker: string; title: string; body?: string; accent?: string }) { return <div className="section-heading reveal"><div className="section-number mono">{index}</div><div><Eyebrow accent={accent}>{kicker}</Eyebrow><h2>{title}</h2>{body && <p>{body}</p>}</div></div>; }
function Page({ view, children }: { view: View; children: React.ReactNode }) { return <main className={`page page-${view}`} key={view}>{children}</main>; }
function Nav({ view, navigate, progress, theme, toggleTheme, contrast, toggleContrast, textScale, cycleTextScale }: { view: View; navigate: (view: View) => void; progress: number; theme: "dark" | "light"; toggleTheme: () => void; contrast: boolean; toggleContrast: () => void; textScale: "default" | "large" | "xlarge"; cycleTextScale: () => void }) { return <header className="site-nav"><div className="reading-progress"><span style={{ width: `${progress}%` }} /></div><button className="brand" onClick={() => navigate("now")}><span>TECH</span><i>//</i><span>SHIFT</span></button><nav>{items.map((item) => <button key={item.id} className={`nav-link ${view === item.id ? "active" : ""}`} onClick={() => navigate(item.id)}><span className="nav-index">{item.index}</span>{item.label}</button>)}</nav><div className="nav-status"><span className="pulse-dot" /><span className="mono">4 MIN READ / {Math.round(progress)}%</span><button className="accessibility-toggle" onClick={cycleTextScale} aria-label={`Text size: ${textScale}`} title={`Text size: ${textScale}. Click to enlarge.`}>A<span>{textScale === "default" ? "" : textScale === "large" ? "+" : "++"}</span></button><button className={`accessibility-toggle ${contrast ? "is-active" : ""}`} onClick={toggleContrast} aria-pressed={contrast} title="Toggle high contrast mode">HC</button><button className="theme-toggle" onClick={toggleTheme} aria-label={`Switch to ${theme === "dark" ? "Light" : "Dark"}`} title={`Theme: ${theme === "dark" ? "Dark" : "Light"}`}><span className="theme-icon">{theme === "dark" ? <Moon size={15} /> : <Sun size={15} />}</span><span className="theme-label">THEME: {theme === "dark" ? "DARK" : "LIGHT"}</span></button></div></header>; }
function Stats() { return <div className="stats-strip reveal">{[["5.4B+", "connected users — over 67% of humanity"], ["300M+", "lines of code in a modern vehicle"], ["175ZB+", "global data generated in recent years"]].map(([value, label]) => <div key={value}><strong>{value}</strong><span>{label}</span></div>)}</div>; }
function Accordion({ title, plain, body, icon: Icon, accent, open, onClick }: { title: string; plain: string; body: string; icon: React.ElementType; accent: string; open: boolean; onClick: () => void }) { return <article className={`accordion-card accent-${accent} technology-card ${open ? "open" : ""}`} data-tooltip={`${title}: ${plain}`}><button onClick={onClick} aria-expanded={open}><span className="accordion-icon"><Icon size={18} /></span><span><strong>{title}</strong><small>PLAIN ENGLISH / {plain}</small></span><ChevronDown size={16} /></button>{open && <div className="accordion-body"><p>{body}</p><span className="mono">WHY IT MATTERS</span></div>}</article>; }


const nowStack = [["AI", "Generative models, machine learning, vision, language, agents, and multimodal reasoning."], ["Cloud", "AWS, Azure, Google Cloud, serverless runtimes, and distributed systems."], ["Data", "Streaming telemetry, data lakes, warehouses, and predictive analytics."], ["Cybersecurity", "Zero-trust identity, threat detection, cloud defense, and AI-assisted response."], ["Robotics", "Industrial automation, autonomous machines, motion planning, and embodied work."], ["Quantum", "Specialized processors, superconducting qubits, and post-quantum cryptography."], ["IoT", "Smart homes, industrial sensors, connected transit, and ambient monitoring."], ["Spatial", "AR, VR, mixed reality, and 3D interfaces anchored to the physical world."]];
const aiActions = ["WRITE", "CODE", "ANALYZE", "SEARCH", "DESIGN", "TEST", "DEBUG", "SUMMARIZE", "PREDICT", "AUTOMATE"];
const futureMap = [["AUTONOMOUS AGENTS", "Core engine", "Systems that plan, use tools, execute, verify, and learn from results."], ["PHYSICAL INTELLIGENCE", "Core engine", "Vision-action models that turn perception into movement in messy spaces."], ["QUANTUM ACCELERATORS", "Core engine", "Specialized co-processors for molecular, material, and route problems."], ["SPATIAL COMPUTING", "Supporting layer", "Environment, voice, gesture, gaze, and context replace the flat screen."], ["EDGE AI", "Supporting layer", "Reasoning runs locally for speed, privacy, and offline resilience."], ["BCI + SYNTHETIC BIOLOGY", "Frontier", "Neural signals and biological code become new interfaces to compute."]];
const darkSectors = [["Banking + finance", "Electronic ledgers, ATMs, and cashless clearing stop. Branches cannot verify balances without centralized data."], ["Healthcare", "Networked monitors, medication controls, patient records, and automated triage become inaccessible."], ["Transportation", "Flight control, maritime routing, rail switches, ports, and fleet telemetry halt for safety."], ["Energy grids", "Real-time load balancing disappears, destabilizing generation, distribution, and cooling."], ["Manufacturing", "Robotized assembly, PLCs, and automated warehouses grind to a halt."], ["Agriculture", "Precision irrigation, sensor networks, and harvest fleets lose coordination."], ["Food distribution", "Supermarkets hold 48–72 hours of inventory; farm-to-fork routing breaks before replenishment."]];
const manualLadder = [["Digital payments", "Physical cash + barter"], ["GPS navigation", "Paper maps + compass"], ["Instant messaging", "Hand-delivered notes"], ["Cloud storage", "Paper ledgers"], ["Automated production", "Hand assembly"]];
const recoverySteps = ["Local voice comms", "Basic grid power", "Mechanical production", "Primitive compute", "Local mesh networks", "Reconnected internet", "Digital civilization"];

function NowPage({ navigate }: { navigate: (view: View) => void }) {
  const [openPillar, setOpenPillar] = useState(() => Number(q("pillar", "0")));
  const [speed, setSpeed] = useState(() => Number(q("speed", "0")));
  const setPillar = (i: number) => { setOpenPillar(i); jump("now", "pillars", { pillar: i }); };
  const setSpeedIndex = (i: number) => { setSpeed(i); jump("now", "acceleration", { speed: i }); };
  return <Page view="now">
    <section className="hero educational-hero hero-now"><div className="hero-grid" /><div className="hero-orbit orbit-one" /><div className="hero-orbit orbit-two" /><div className="hero-content container"><div className="hero-meta reveal"><span>FIELD NOTE 001 / ORIENTATION</span><span>APPROX. 04 MIN</span></div><div className="hero-kicker reveal"><span className="pulse-dot" /> A PLAIN-ENGLISH TOUR OF INFORMATION TECHNOLOGY</div><h1 className="hero-title reveal">THE ENGINE<br /><em>BENEATH</em><br /><span>MODERN REALITY.</span></h1><div className="hero-bottom reveal"><p>Everything you interact with — from the sensor that turns on a tap to the transoceanic cables routing your messages — is powered by Information Technology. It is the operating system of human society.</p><button className="outline-button" onClick={() => document.getElementById("pillars")?.scrollIntoView({ behavior: "smooth" })}>START THE TOUR <ArrowDown size={16} /></button></div></div></section>
    <section className="section container"><Stats /></section>
    <section className="section section-tinted" id="it-map"><div className="container"><Heading index="01B / 08" kicker="The paradigm shift" title="IT is no longer just computers." body="The old chain was computers → software → internet. The modern stack is a living infrastructure for civilization." />
      <div className="relative overflow-hidden rounded-2xl border border-[var(--border-color)] bg-[var(--bg-surface)] shadow-md group my-8 max-w-3xl mx-auto">
        <img src={`\$\{import.meta.env.BASE_URL\}images/page01-global-infrastructure.jpg`} alt="Global connected IT infrastructure" loading="lazy" className="w-full h-auto object-cover aspect-[16/10] transition-transform duration-500 group-hover:scale-102" />
      </div>
      <div className="paradigm-compare reveal"><div><span className="mono">BEFORE</span><strong>Computers → Software → Internet</strong></div><ArrowRight size={20} /><div><span className="mono">TODAY</span><strong>AI + Cloud + Data + Robotics + Cybersecurity + Automation + IoT</strong></div></div><div className="stack-tree reveal"><div><span className="tree-label">DIGITAL</span><strong>Software · Internet · Apps</strong></div><div><span className="tree-label">INTELLIGENCE</span><strong>AI · ML · Agents</strong></div><div><span className="tree-label">INFRASTRUCTURE</span><strong>Cloud · Networks · Data centers</strong></div></div></div></section>
    <section className="section container" id="pillars"><Heading index="01 / 04" kicker="The four pillars of IT" title="Think of IT as a modern house." body="The jargon is only intimidating until you can see the structure. Tap each layer to open the plain-English version." /><div className="accordion-grid">{pillars.map(([title, plain, body, why, accent, Icon], i) => <Accordion key={title} title={title} plain={plain} body={`${body} ${why}`} accent={accent} icon={Icon} open={openPillar === i} onClick={() => setPillar(i)} />)}</div><div className="plain-note reveal"><span className="mono">THE HOUSE RULE</span><strong>Every layer depends on the one below it.</strong><p>Software cannot run without hardware. AI cannot learn without data. And none of it can move without networks.</p></div></section>
    <section className="section section-tinted" id="acceleration"><div className="container"><Heading index="02 / 04" kicker="Why technology accelerates" title="Four forces keep feeding one another." body="This is a compounding feedback loop, not a single breakthrough. Select a factor to see the leverage point." />
      <div className="relative overflow-hidden rounded-2xl border border-[var(--border-color)] bg-[var(--bg-surface)] shadow-md group my-8 max-w-3xl mx-auto">
        <img src={`\$\{import.meta.env.BASE_URL\}images/page01-chip-war.jpg`} alt="Advanced semiconductor processor" loading="lazy" className="w-full h-auto object-cover aspect-[16/10] transition-transform duration-500 group-hover:scale-102" />
      </div>
      <div className="acceleration-layout reveal"><div className="factor-list">{acceleration.map(([number, title, label], i) => <button key={number} className={speed === i ? "selected" : ""} onClick={() => setSpeedIndex(i)}><span>{number}</span><strong>{title}</strong><small>{label}</small></button>)}</div><div className="factor-detail"><span className="mono">FACTOR / {acceleration[speed][0]}</span><h3>{acceleration[speed][1]}</h3><p>{acceleration[speed][3]}</p><div className="feedback-arrow"><span>more capability</span><ArrowRight size={16} /><span>more possibility</span></div><small>{acceleration[speed][4]}</small></div></div></div></section>
    <section className="section container" id="ai-layer"><Heading index="03 / 04" kicker="AI in 2026" title="AI is becoming a layer, not a feature." body="The same underlying capability shows up differently depending on the discipline it touches." /><div className="ai-field-grid">{aiFields.map(([title, body, Icon, accent], i) => <article className={`ai-field-card accent-${accent} reveal`} key={title} style={{ animationDelay: `${i * 50}ms` }}><Icon size={21} /><span className="mono">0{i + 1}</span><h3>{title}</h3><p>{body}</p><ArrowUpRight size={15} /></article>)}</div></section>
    <section className="section section-tinted" id="ai-actions"><div className="container"><Heading index="03B / 08" kicker="The biggest shift" title="AI didn’t just join IT. AI is changing it." body="The action matrix is moving from passive answers toward systems that plan, use software tools, and perform work." />
      <div className="relative overflow-hidden rounded-2xl border border-[var(--border-color)] bg-[var(--bg-surface)] shadow-md group my-8 max-w-3xl mx-auto">
        <img src={`\$\{import.meta.env.BASE_URL\}images/page01-ai-developer.jpg`} alt="Augmented AI developer environment" loading="lazy" className="w-full h-auto object-cover aspect-[16/10] transition-transform duration-500 group-hover:scale-102" />
      </div>
      <div className="action-matrix reveal">{aiActions.map((action, i) => <span key={action} style={{ "--i": i } as React.CSSProperties}>{action}</span>)}</div><div className="human-ai-grid reveal"><article><Tag accent="violet">AI STRENGTHS</Tag><p>Raw speed, massive scale, tireless pattern recognition, routine automation, and 24/7 availability.</p></article><article><Tag accent="cyan">HUMAN STRENGTHS</Tag><p>Critical judgment, novel creativity, cultural context, moral ethics, leadership, empathy, and responsibility.</p></article></div><div className="plain-note"><span className="mono">CORE TAKEAWAY</span><strong>The competition is not human vs. AI.</strong><p>It is people using AI versus people who do not.</p></div></div></section>
    <section className="section container" id="daily-life"><div className="container"><Heading index="04 / 04" kicker="Daily life reality check" title="Your morning coffee has a hidden IT chain." body="The point is not that everything is magical. It is that everything is connected." /><div className="coffee-table reveal"><div className="coffee-row coffee-head"><span>EVENT</span><span>TECHNICAL LAYER</span><span>PLAIN ENGLISH</span></div>{coffee.map(([event, layer, explanation]) => <div className="coffee-row" key={event}><strong>{event}</strong><span className="mono">{layer}</span><p>{explanation}</p></div>)}</div><div className="transition-cta reveal"><div><Eyebrow accent="violet">Next chapter</Eyebrow><h3>NOW THAT YOU SEE THE MACHINE RUNNING...</h3><p>What happens when it outgrows our current blueprints?</p></div><button className="primary-button button-violet" onClick={() => navigate("future")}>ENTER 2030: THE NEXT ERA <ArrowRight size={17} /></button></div></div></section>
  </Page>;
}

function FuturePage({ navigate }: { navigate: (view: View) => void }) {
  const [openShift, setOpenShift] = useState(() => Number(q("shift", "0")));
  const [filter, setFilter] = useState(() => q("filter", "ALL"));
  const visible = filter === "ALL" ? frontiers : frontiers.filter((x) => x[1] === filter);
  const softwareEras = [["1980s–2010s", "SYNTAX ERA", "Developers memorize C, Java, and Python. A missing bracket can break the whole program."], ["2020–2025", "ASSISTED ERA", "Programmers write prompts and snippets while AI autocompletes lines and generates functions."], ["2030", "INTENT ERA", "Engineers declare business logic, security policies, and performance budgets. Agent swarms draft, test, and deploy the system."]];
  const agentRows: [string, string, string[]][] = [["Current conversational AI", "PASSIVE", ["Needs constant human prompts", "Generates text answers", "Little cross-session state"]], ["2030 agent swarms", "ACTIVE + PROACTIVE", ["Self-plans and uses tools", "Agents cross-verify each other", "Humans approve high-impact edge cases"]]];
  return <Page view="future">
    <section className="hero educational-hero hero-future"><div className="future-scanlines" /><div className="hero-content container"><div className="hero-meta reveal"><span>FIELD NOTE 002 / PROJECTION</span><span>APPROX. 04 MIN</span></div><div className="hero-kicker reveal"><span className="pulse-dot" /> FOLLOW THE FOOTPRINTS / CALIBRATE YOUR CERTAINTY</div><h1 className="hero-title reveal">THE DISSOLUTION<br /><em>OF THE</em><br /><span>COMPUTER.</span></h1><div className="hero-bottom reveal"><p>By 2030, computing leaves behind small handheld screens. It transforms into ambient intelligence — intent-driven, invisible, and physically embodied in the space around us.</p><div className="certainty-legend"><Tag accent="lime">HIGH CONFIDENCE / LIKELY</Tag><Tag accent="amber">MEDIUM CONFIDENCE / PLAUSIBLE</Tag><Tag accent="red">FRONTIER / SPECULATIVE</Tag></div></div></div></section>
    <section className="section section-tinted" id="future-map"><div className="container"><Heading index="00 / 16" kicker="Welcome to 2030" title="A trajectory, not a destination." body="Prediction is not fact. Use the confidence tags as a map of evidence, uncertainty, and frontier possibility." accent="violet" />
      <div className="relative overflow-hidden rounded-2xl border border-[var(--border-color)] bg-[var(--bg-surface)] shadow-md group my-8 max-w-3xl mx-auto">
        <img src={`\$\{import.meta.env.BASE_URL\}images/page02-spatial-computing.jpg`} alt="Spatial computing and ambient intelligence" loading="lazy" className="w-full h-auto object-cover aspect-[16/10] transition-transform duration-500 group-hover:scale-102" />
      </div>
      <div className="future-map-grid">{futureMap.map(([title, type, body], i) => <article className="future-map-card reveal" key={title}><Tag accent={type === "Core engine" ? "violet" : type === "Frontier" ? "red" : "lime"}>{type}</Tag><span className="mono">0{i + 1}</span><h3>{title}</h3><p>{body}</p></article>)}</div><div className="execution-loop reveal">{["PROMPT", "REASON", "PLAN", "USE TOOLS", "EXECUTE", "VERIFY", "LEARN"].map((x, i) => <span key={x}><b>{String(i + 1).padStart(2, "0")}</b>{x}{i < 6 && <ArrowRight size={14} />}</span>)}</div></div></section>
    <section className="section container" id="intent-development"><Heading index="01 / 05" kicker="Evolution of software engineering" title="Intent becomes the new syntax." body="The language changes. The responsibility does not: someone still has to define what good means." accent="violet" /><div className="era-grid reveal">{softwareEras.map(([period, title, body], i) => <article className={`era-card era-${i}`} key={period}><span className="mono">{period}</span><Tag accent={i === 2 ? "violet" : i === 1 ? "amber" : "cyan"}>{title}</Tag><h3>{i === 0 ? "Syntax" : i === 1 ? "Assistance" : "Architecture"}</h3><p>{body}</p>{i === 2 && <div className="era-callout"><Check size={15} /> 80% of the work shifts toward design, verification, security, and business logic.</div>}</article>)}</div><div className="plain-note reveal"><span className="mono">THE BIG SHIFT</span><strong>From writing functions to designing systems.</strong><p>Boilerplate becomes cheap. Judgment, constraints, threat modeling, and verification become the scarce skills.</p></div></section>
    <section className="section section-tinted" id="agent-swarms"><div className="container"><Heading index="02 / 05" kicker="Autonomous agent swarms" title="A chatbot answers. A swarm operates." body="The difference is not personality. It is state, tool use, delegation, and accountability." accent="violet" /><div className="agent-compare reveal">{agentRows.map(([title, state, bullets], i) => <article className={`agent-compare-card agent-${i}`} key={title}><div className="agent-card-top"><Tag accent={i === 0 ? "amber" : "violet"}>{state}</Tag><span className="mono">0{i + 1}</span></div><h3>{title}</h3><ul>{bullets.map((bullet) => <li key={bullet}><Check size={14} />{bullet}</li>)}</ul><p>{i === 0 ? "You ask, it responds, you execute." : "You define the objective; specialized agents plan, negotiate, verify, and surface only the decisions that need human approval."}</p></article>)}</div><div className="agent-scenario reveal"><span className="mono">SCENARIO / CLOUD COST AUDIT</span><strong>“Audit cloud spending, find idle clusters, test downtime risk, and spin them down during non-peak hours.”</strong><div><span>Security Agent audits</span><ArrowRight size={15} /><span>Feature Agent drafts</span><ArrowRight size={15} /><span>DevOps Agent deploys</span></div></div></div></section>
    <section className="section container" id="embodiment"><Heading index="03 / 05" kicker="Physical intelligence" title="Software gets a body." body="Foundation vision-action models let AI navigate three-dimensional spaces, not only digital text." accent="violet" />
      <div className="relative overflow-hidden rounded-2xl border border-[var(--border-color)] bg-[var(--bg-surface)] shadow-md group my-8 max-w-3xl mx-auto">
        <img src={`\$\{import.meta.env.BASE_URL\}images/page02-humanoid-robotics.jpg`} alt="Embodied artificial intelligence" loading="lazy" className="w-full h-auto object-cover aspect-[16/10] transition-transform duration-500 group-hover:scale-102" />
      </div>
      <div className="embodiment-grid reveal"><div className="embodiment-visual"><div className="spatial-orbit" /><div className="spatial-core"><Cpu size={28} /><span>VISION<br />→ ACTION</span></div><div className="spatial-label spatial-a">WAREHOUSE / LOGISTICS</div><div className="spatial-label spatial-b">CARE / ASSISTANCE</div><div className="spatial-label spatial-c">AGRICULTURE / PICKING</div></div><div className="embodiment-copy"><h3>Adaptive, not pre-programmed.</h3><p>Warehouse robots, construction machines, delivery drones, and care assistants learn from physical demonstrations. The environment is no longer a fixed set of rules — it is a changing context to interpret.</p><div className="ambient-callout"><Globe2 size={17} /><span>A technician looking at an aircraft engine sees live thermal diagnostics anchored directly to the machinery.</span></div></div></div></section>
    <section className="section section-tinted" id="hardware-frontier"><div className="container"><Heading index="04 / 05" kicker="The next hardware frontier" title="Beyond traditional silicon." body="The useful question is not “Is it faster?” It is “What new constraints does it remove?”" accent="violet" />
      <div className="relative overflow-hidden rounded-2xl border border-[var(--border-color)] bg-[var(--bg-surface)] shadow-md group my-8 max-w-3xl mx-auto">
        <img src={`\$\{import.meta.env.BASE_URL\}images/page02-quantum-accelerator.jpg`} alt="Quantum acceleration and new hardware frontiers" loading="lazy" className="w-full h-auto object-cover aspect-[16/10] transition-transform duration-500 group-hover:scale-102" />
      </div>
      <div className="hardware-grid reveal"><article><BrainCircuit size={21} /><Tag accent="violet">NEUROMORPHIC</Tag><h3>Brains, not clocks.</h3><p>Event-based chips draw power only when incoming signals change, making local reasoning practical for wearables, implants, and drones.</p><strong>DAYS OR WEEKS OF BATTERY LIFE</strong></article><article><Binary size={21} /><Tag accent="amber">QUANTUM</Tag><h3>A specialist, not a replacement.</h3><p>Quantum systems act as cloud co-processors for molecular simulation, battery chemistry, and global route optimization.</p><strong>NEW PROBLEM CLASSES</strong></article><article><Wifi size={21} /><Tag accent="lime">EDGE AI</Tag><h3>Compute comes home.</h3><p>Reasoning runs locally on rings, traffic sensors, and medical devices — reducing latency and keeping sensitive data closer to its source.</p><strong>DATA SOVEREIGNTY</strong></article></div></div></section>
    <section className="section section-tinted" id="programming-3"><div className="container"><Heading index="05B / 16" kicker="Programming 3.0" title="The interface moves from syntax to intent." body="Python, C++, and JavaScript will not vanish overnight. But human language plus formal constraints become the primary interface for construction." accent="violet" /><div className="programming-ladder reveal">{[["Programming 1.0", "Machine-oriented", "Punch cards · Assembly · direct hardware control"], ["Programming 2.0", "Developer-oriented", "C · Java · Python · high-level abstractions"], ["Programming 3.0", "Intent + AI-oriented", "Constraints · behaviors · verification rules"]].map(([version, title, body], i) => <article key={version}><span className="mono">0{i + 1}</span><Tag accent={i === 2 ? "violet" : "cyan"}>{version}</Tag><h3>{title}</h3><p>{body}</p></article>)}</div></div></section>
    <section className="section container" id="career-evolution"><Heading index="05 / 05" kicker="Job market + career evolution" title="The work moves up the stack." body="Some repetitive tasks decline. The work of designing, auditing, securing, and humanizing systems multiplies." accent="violet" /><div className="jobs-grid expanded-jobs">{[["Roles declining", "Rote syntax coding, manual test scripts, basic formatting, repetitive scraping", "red"], ["AI Agent Architect", "Designs workflows, permissions, and tool ecosystems for multi-agent systems.", "violet"], ["AI Safety + Algorithmic Auditor", "Evaluates bias, hallucination rates, and regulatory compliance.", "lime"], ["Cyber-Physical Systems Engineer", "Secures municipal grids, robotic fleets, and medical hardware.", "cyan"], ["Human-AI Interaction Designer", "Creates intuitive feedback loops for non-technical users.", "amber"]].map(([title, body, accent], i) => <article className={`job-card accent-${accent} reveal`} key={title}><span className="mono">0{i + 1}</span><h3>{title}</h3><p>{body}</p></article>)}</div><div className="transition-cta dark-cta reveal"><div><Eyebrow accent="red">Final question</Eyebrow><h3>WHAT HAPPENS IF THE PLUG IS PULLED?</h3><p>We are building the most powerful technological web in human history. That makes resilience part of the design brief.</p></div><button className="primary-button button-red" onClick={() => navigate("dark")}>ENTER THE DARK SIDE <ArrowRight size={17} /></button></div></section>
  </Page>;
}

const antifragility: [string, string, string][] = [["🔄 Redundancy", "Never let one server, data center, or routing vendor hold the keys to critical life support.", "Municipal utilities, hospitals, and air transit networks need secondary and tertiary failover systems that activate instantly."], ["💾 Offline Backups", "Critical information must not exist solely in the cloud.", "Medical histories, land titles, legal records, and emergency manuals need immutable physical or local copies disconnected from the public internet."], ["📡 Alternative Communication", "When fiber cables and cell towers fail, voice and emergency dispatch cannot go silent.", "Maintain HAM networks, high-frequency transceivers, mesh radios, and point-to-point satellite links dedicated to disaster recovery."], ["⚡ Resilient Power", "Information technology is dead silicon without electricity.", "Water plants, trauma centers, and telecom hubs need solar, geothermal, hydrogen, or other decentralized power that survives national-grid failures."], ["👨‍🔧 Human Skills", "Software should assist people, never replace capability entirely.", "Pilots, railway managers, grid dispatchers, and surgeons need mandatory analog drills with valves, charts, and manual switches."], ["🛡️ Cybersecurity", "Treat critical civic infrastructure as sovereign defense ground.", "Disconnect grids, water plants, and nuclear systems from public access; enforce Zero Trust hardware authentication and post-quantum protocols."], ["🤖 Responsible AI", "Never surrender final life-or-death decisions to opaque automation.", "Infrastructure, medical, and emergency systems need fail-safe testing, legal accountability, and non-bypassable manual kill switches."], ["🌍 Decentralization", "Avoid hyper-centralized monopolistic choke points.", "Invest in open protocols, municipal software stacks, and distributed data architectures instead of a handful of hyperscalers."]];

function DarkPage() {
  const [selected, setSelected] = useState(() => Number(q("hour", "0")));
  const [openCause, setOpenCause] = useState(() => { const raw = Number(q("cause", q("pillar", "0"))); return Number.isFinite(raw) && raw >= 0 && raw < vulnerabilities.length ? raw : 0; });
  return <Page view="dark">
    <section className="hero educational-hero hero-dark"><div className="dark-vignette" /><div className="hero-content container"><div className="hero-meta reveal"><span>FIELD NOTE 003 / FAILURE MODE</span><span>APPROX. 04 MIN</span></div><div className="hero-kicker red-kicker reveal"><CircleAlert size={14} /> SIMULATED TERMINAL HEARTBEAT / SYSTEM OFFLINE</div><h1 className="dark-title reveal">THE FRAGILITY<br /><em>OF THE</em><br /><span>INVISIBLE.</span></h1><div className="dark-copy reveal"><p>Modern humans do not live in raw nature. We live inside a high-tech life-support system. If information technology fails tomorrow, the challenge is not losing social media — it is maintaining clean water, food supply chains, and power.</p><strong>NO IT.</strong></div></div></section>
    <section className="section dark-section" id="shutdown"><div className="container"><Heading index="00 / 14" kicker="The total shutdown" title="The world does not go dark. The world goes manual." body="Every database lock, cloud server, digital switch, and automated control loop halts simultaneously." accent="red" />
      <div className="relative overflow-hidden rounded-2xl border border-[var(--border-color)] bg-[var(--bg-surface)] shadow-md group my-8 max-w-3xl mx-auto">
        <img src={`\$\{import.meta.env.BASE_URL\}images/page03-port-blackout.jpg`} alt="Global logistics and port blackout" loading="lazy" className="w-full h-auto object-cover aspect-[16/10] transition-transform duration-500 group-hover:scale-102" />
      </div>
      <div className="shutdown-lines reveal">{["NO INTERNET.", "NO COMPUTERS.", "NO SOFTWARE.", "NO DIGITAL NETWORKS.", "NO INFORMATION TECHNOLOGY."].map((line, i) => <span key={line} style={{ "--i": i } as React.CSSProperties}>{line}</span>)}</div><div className="first-shock reveal"><span className="mono">THE FIRST SECOND → THE FIRST HOUR</span><p>Local signals vanish. Point-of-sale systems freeze. Web apps fail, GPS drops, and electronic doors default to fail-safe locks.</p></div></div></section>
    <section className="section dark-section" id="outage"><div className="container"><Heading index="01 / 03" kicker="The cascading 72-hour failure chain" title="The outage becomes legible by the hour." body="Select a moment. The system does not collapse in one cinematic instant — it cascades." accent="red" /><div className="outage-timeline reveal">{outage.map(([time, title, note], i) => <button key={time} className={`outage-step ${selected === i ? "selected" : ""}`} onClick={() => { setSelected(i); jump("dark", "outage", { hour: i }); }}><span className="outage-dot" /><span className="mono">HOUR {time}</span><strong>{title}</strong><small>{note}</small><span className="outage-tooltip">{note}</span></button>)}</div><div className="outage-readout reveal"><span className="mono">SELECTED / HOUR {outage[selected][0]}</span><h3>{outage[selected][1]}</h3><p>{outage[selected][2]}</p></div></div></section>
    <section className="section dark-section dark-section-muted" id="sectors"><div className="container"><Heading index="01B / 14" kicker="Sectors that collapse" title="Nothing fails in isolation." body="The first 24 hours are not an apocalypse movie. They are a sequence of systems losing their shared coordination layer." accent="red" /><div className="sector-grid">{darkSectors.map(([title, body], i) => <article className="sector-card reveal" key={title}><span className="mono">0{i + 1} / CRITICAL</span><h3>{title}</h3><p>{body}</p></article>)}</div><div className="cascade-chain reveal">{["IT FAILURE", "COMMUNICATION", "BUSINESS", "LOGISTICS", "SUPPLY CHAIN", "SHORTAGES", "ECONOMIC CRISIS"].map((x, i) => <span key={x}>{x}{i < 6 && <ArrowRight size={14} />}</span>)}</div></div></section>
    <section className="section dark-section dark-section-muted" id="vulnerability"><div className="container"><Heading index="02 / 03" kicker="Why society is so vulnerable" title="The weak point is the web between systems." body="These are structural causes, not moral failures. Tap a cause to unpack the dependency." accent="red" /><div className="cause-grid">{vulnerabilities.map(([title, body], i) => <article className={`cause-card ${openCause === i ? "open" : ""}`} key={title}><button onClick={() => { setOpenCause(i); jump("dark", "vulnerability", { cause: i, pillar: i }); }}><span className="mono">0{i + 1}</span><strong>{title}</strong><ChevronDown size={15} /></button><p className="cause-summary">{vulnerabilitySummaries[i]}</p><div className={`cause-expand ${openCause === i ? "expanded" : ""}`}><p>{body}</p><span className="mono">DEPENDENCY BREAKDOWN / {openCause === i ? "VISIBLE" : "READY"}</span></div></article>)}</div></div></section>
    <section className="section dark-section" id="reversion"><div className="container"><Heading index="03B / 14" kicker="The great reversion" title="Digital becomes manual." body="Human knowledge, physical machinery, books, tools, and face-to-face cooperation survive. The workflow changes." accent="lime" />
      <div className="relative overflow-hidden rounded-2xl border border-[var(--border-color)] bg-[var(--bg-surface)] shadow-md group my-8 max-w-3xl mx-auto">
        <img src={`\$\{import.meta.env.BASE_URL\}images/page03-analog-command.jpg`} alt="Analog command and manual tools reversion" loading="lazy" className="w-full h-auto object-cover aspect-[16/10] transition-transform duration-500 group-hover:scale-102" />
      </div>
      <div className="manual-ladder reveal">{manualLadder.map(([digital, manual], i) => <div key={digital}><strong>{digital}</strong><ArrowRight size={16} /><span>{manual}</span></div>)}</div><Heading index="03C / 14" kicker="Recovery ladder" title="Can humanity rebuild?" body="Recovery is phased: reconnect people first, then the systems that let people coordinate." accent="lime" /><div className="recovery-steps reveal">{recoverySteps.map((step, i) => <span key={step}><b>0{i + 1}</b>{step}</span>)}</div></div></section>
    <section className="section dark-section" id="resilience"><div className="container"><Heading index="04 / 04" kicker="Reconstruction / architecture of survival" title="THE SOLUTION: BUILD A RESILIENT DIGITAL WORLD" body="The idea is not to remove technology or retreat into the past. Technology has elevated human health, communication, and prosperity to unprecedented heights. The objective is to make civilization less dangerously dependent on a fragile, single digital point of failure. We must build digital antifragility." accent="lime" />
      <div className="relative overflow-hidden rounded-2xl border border-[var(--border-color)] bg-[var(--bg-surface)] shadow-md group my-8 max-w-3xl mx-auto">
        <img src={`\$\{import.meta.env.BASE_URL\}images/page03-resilient-grid.jpg`} alt="Decentralized microgrid and resilient architecture" loading="lazy" className="w-full h-auto object-cover aspect-[16/10] transition-transform duration-500 group-hover:scale-102" />
      </div>
      <div className="antifragility-grid">{antifragility.map(([title, principle, practice], i) => <article className="antifragility-card reveal" key={title}><div className="antifragility-icon" aria-hidden="true"><Check size={20} /></div><span className="mono">0{i + 1} / PILLAR</span><h3>{title}</h3><strong>{principle}</strong><p>{practice}</p></article>)}</div><div className="realization-banner reveal"><span className="mono">CORE REALIZATION</span><strong>The goal isn’t a world without technology.<br />The goal is a world that can survive when technology fails.</strong></div></div></section>
    <section className="section final-blackout"><div className="container"><div className="final-screen final-screen-manifesto reveal"><span className="mono">FINAL TRANSMISSION / 04</span><p className="manifesto-kicker">WHAT IS HAPPENING? / WHAT COULD HAPPEN NEXT? / WHAT IF IT ALL DISAPPEARED?</p><h2>THE FUTURE IS NOT SOMETHING<br /><em>WE DISCOVER.</em></h2><h3>IT IS SOMETHING WE DESIGN.</h3><p>Technology will shape the future.<br />The question is whether we shape technology first.</p><div className="final-mark"><span>TECH</span><i>//</i><span>SHIFT</span></div></div></div></section>
  </Page>;
}

export default function Home() {
  const [view, setView] = useState<View>(() => { const h = window.location.hash.replace("#", "") as View; return ["now", "future", "dark"].includes(h) ? h : "now"; });
  const [progress, setProgress] = useState(0);
  const [theme, setTheme] = useState<"dark" | "light">(() => { const saved = localStorage.getItem("tech-shift-theme"); return saved === "light" || saved === "pitch" ? "light" : "dark"; });
  const [contrast, setContrast] = useState(() => localStorage.getItem("tech-shift-contrast") === "high");
  const [textScale, setTextScale] = useState<"default" | "large" | "xlarge">(() => { const saved = localStorage.getItem("tech-shift-text-scale"); return saved === "large" || saved === "xlarge" ? saved : "default"; });
  useEffect(() => { const onHash = () => { const h = window.location.hash.replace("#", "") as View; if (["now", "future", "dark"].includes(h)) setView(h); }; window.addEventListener("hashchange", onHash); return () => window.removeEventListener("hashchange", onHash); }, []);
  useEffect(() => { document.documentElement.dataset.theme = theme; localStorage.setItem("tech-shift-theme", theme); }, [theme]);
  useEffect(() => { document.documentElement.dataset.contrast = contrast ? "high" : "standard"; localStorage.setItem("tech-shift-contrast", contrast ? "high" : "standard"); }, [contrast]);
  useEffect(() => { document.documentElement.dataset.textScale = textScale; localStorage.setItem("tech-shift-text-scale", textScale); }, [textScale]);
  useEffect(() => { const onScroll = () => { const max = document.documentElement.scrollHeight - window.innerHeight; setProgress(max > 0 ? (window.scrollY / max) * 100 : 0); }; onScroll(); window.addEventListener("scroll", onScroll, { passive: true }); document.body.dataset.view = view; const section = q("section", ""); window.setTimeout(() => { if (section) document.getElementById(section)?.scrollIntoView({ behavior: "smooth", block: "start" }); const observer = new IntersectionObserver((entries) => entries.forEach((entry) => entry.isIntersecting && entry.target.classList.add("is-visible")), { threshold: .06 }); document.querySelectorAll(".reveal").forEach((el) => observer.observe(el)); }, 70); return () => window.removeEventListener("scroll", onScroll); }, [view]);
  const navigate = (next: View) => { setView(next); linkState(next); window.scrollTo({ top: 0, behavior: "smooth" }); };
  return <div className={`site-shell theme-${theme}`}><Nav view={view} navigate={navigate} progress={progress} theme={theme} toggleTheme={() => setTheme((current) => current === "dark" ? "light" : "dark")} contrast={contrast} toggleContrast={() => setContrast((current) => !current)} textScale={textScale} cycleTextScale={() => setTextScale((current) => current === "default" ? "large" : current === "large" ? "xlarge" : "default")} /><div className="side-index"><span className="mono">0{items.findIndex((i) => i.id === view) + 1}</span><span className="side-line" /><span className="mono">03</span></div>{view === "now" && <NowPage navigate={navigate} />}{view === "future" && <FuturePage navigate={navigate} />}{view === "dark" && <DarkPage />}<footer className="site-footer"><span>TECH//SHIFT</span><span className="mono">UNDERSTANDING INFORMATION TECHNOLOGY</span><span className="mono">© 2025 / OPEN SIGNAL</span></footer></div>;
}

export { Home };
